// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[itemError-0]
	_ = x[itemEOF-1]
	_ = x[itemWhitespace-2]
	_ = x[itemComment-3]
	_ = x[itemString-4]
	_ = x[itemTrue-5]
	_ = x[itemFalse-6]
	_ = x[itemNull-7]
	_ = x[itemArrayOpen-8]
	_ = x[itemArrayClose-9]
	_ = x[itemComma-10]
	_ = x[itemObjectOpen-11]
	_ = x[itemObjectClose-12]
	_ = x[itemColon-13]
	_ = x[itemNumber-14]
}

const _itemType_name = "itemErroritemEOFitemWhitespaceitemCommentitemStringitemTrueitemFalseitemNullitemArrayOpenitemArrayCloseitemCommaitemObjectOpenitemObjectCloseitemColonitemNumber"

var _itemType_index = [...]uint8{0, 9, 16, 30, 41, 51, 59, 68, 76, 89, 103, 112, 126, 141, 150, 160}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
